### ISSUE TITLE
Create new releases for Bower

### ISSUE THREAD

**Issue by davidpaulsson** [syntaqx/pass-meter#2]
Hey, thank you for a nice little lib. Could you create a new release (v1.0.1) so that Bower detects it? If I `bower install pass-meter` it downloads 1.0.0 since that's the [newest release](https://github.com/syntaqx/pass-meter/releases).

**Comment by syntaqx** [comment]
Glad you enjoy the repository. Haven't really looked at this in a while, but I've tagged the latest master for you! https://github.com/syntaqx/pass-meter/releases/tag/1.0.1

Feel free to send any pull requests or request additional features if you enjoy the package.
