### ISSUE TITLE
Plugin Combination with ShowPassword

### ISSUE THREAD

**Issue by seularts** [syntaqx/pass-meter#4]
I'm combining your plugin with this one: https://github.com/wenzhixin/bootstrap-show-password
Everything works great except one particular thing. When I press to show the password, the password input is switched with a cloned text input with its value. For the life of me, I can't make your password meter read the value in that cloned text input. The funny thing is that when I hide the password back (and disable the text input showing only the password input), the password meter continues calculating the strength in the password type input. Can you give me a solution or a reason to why this is happening!?

I even set up a unique custom attribute to pass from the password input to the cloned text input, such as pass-strength="on" and then use:

`/* Password strength bar and dynamic color */
	$('input[pass-strength="on"]').passMeter(function (score) {
	$('.jquery-result-1 .progress-bar').width(score + '%');

	if(score < 40) {
		$('.progress-bar').addClass('bg-danger');
	}
	else if(score > 40 && score <80) {
	  	$('.progress-bar').addClass('bg-warning').removeClass('bg-danger');
	}
	else if(score > 80) {
	  	$('.progress-bar').addClass('bg-success').removeClass('bg-warning');
	}
	});`

**Comment by seularts** [comment]
I figured it out. The bar can't read the values if the input text was appended in the code. I had to manually create that field to mirror the values so it can read correctly.

**Comment by syntaqx** [comment]
Glad you were able to figure things out! Sorry for not responding sooner, currently rocking a cold. Going to close this out.
